[`docs`] Fix doc build problems (part 1) (#3811)
* Docs: Add missing `sphinx_rtd_theme` dependency to `docs` group

This resolves a local docs build error:

```console
$ python -m venv venv-docs
$ source venv-docs/bin/activate
$ python -m pip install --group=docs
$ make docs

...

no theme named 'sphinx_rtd_theme' found (missing theme.toml?)

...

$ deactivate
```

* Docs: Update a redirecting PyTorch intersphinx mapping

This resolves an info message when building the docs:

```
intersphinx inventory has moved: https://pytorch.org/docs/stable/objects.inv -> https://docs.pytorch.org/docs/stable/objects.inv
```

* Docs: Resolve two autodoc warnings

The warnings are:

```
WARNING: missing attribute modality_config in object sentence_transformers.base.modules.Transformer [autodoc]
WARNING: missing attribute transformer_task in object sentence_transformers.base.modules.Transformer [autodoc]
```

While these attributes exist on instances,
they are not methods nor properties.

* Docs: Resolve a docutils warning

The warning is:

```
sentence_transformers/sentence_transformer/losses/multiple_negatives_ranking.py:
docstring of sentence_transformers.sentence_transformer.losses.multiple_negatives_ranking.MultipleNegativesRankingLoss:52:
ERROR: Unexpected indentation. [docutils]
```

RST requires nested lists to be separated by blank lines.

* Docs: Resolve a docutils warning

The warning is:

```
sentence_transformers/sentence_transformer/losses/cached_multiple_negatives_ranking.py:
docstring of sentence_transformers.sentence_transformer.losses.cached_multiple_negatives_ranking.CachedMultipleNegativesRankingLoss:46:
ERROR: Unexpected indentation. [docutils]
```

RST requires nested lists to be separated by blank lines.

* Docs: Resolve a Sphinx TOC warning

The warning is:

```
docs/package_reference/sparse_encoder/index.rst:4:
WARNING: toctree contains reference to nonexisting document
'docs/package_reference/sentence_transformer/sampler' [toc.not_readable]
```

The `sampler.md` file was moved in commit `4cdbd836717e420e3b4c2ea72c894fb1e2120100`.

* Docs: Resolve a docutils warning

The warning is:

```
sentence_transformers/sparse_encoder/model.py:
docstring of sentence_transformers.sparse_encoder.model.SparseEncoder.decode:12:
ERROR: Unexpected indentation. [docutils]
```

The root issue was the formatting of the conditional return types.
Sphinx could not handle two type annotations on separate lines,
and ultimately rendered the content incorrectly.

* Docs: Resolve 3 docutils warnings

The warnings are:

```
index.rst:7: WARNING: Duplicate explicit target name: "quickstart". [docutils]
index.rst:7: WARNING: Duplicate explicit target name: "quickstart". [docutils]
index.rst:17: WARNING: Duplicate explicit target name: "quickstart". [docutils]
```

The issue is that links created with a single trailing underscore
are registered with Sphinx. The solution is to use two trailing underscores
which create anonymous links.

This avoids the "duplicate explicit target name" warning.

* Anonymize 4th quickstart + update sphinx_rtd_theme version

Co-authored-by: Tom Aarsen <37621491+tomaarsen@users.noreply.github.com>

---------

Co-authored-by: Tom Aarsen <37621491+tomaarsen@users.noreply.github.com>